//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceModel.ConferenceVersionWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConferenceVersionWebservice.ConferenceVersionWebserviceSoap")]
    public interface ConferenceVersionWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpDateFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity GetUpDateFile();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetUpDateFile", ReplyAction="*")]
        System.IAsyncResult BeginGetUpDateFile(System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity EndGetUpDateFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NeedVersionUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool NeedVersionUpdate(string PC_Version);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/NeedVersionUpdate", ReplyAction="*")]
        System.IAsyncResult BeginNeedVersionUpdate(string PC_Version, System.AsyncCallback callback, object asyncState);
        
        bool EndNeedVersionUpdate(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConferenceVersionUpdateEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string updateFileField;
        
        private string updateRootFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UpdateFile {
            get {
                return this.updateFileField;
            }
            set {
                this.updateFileField = value;
                this.RaisePropertyChanged("UpdateFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UpdateRootFile {
            get {
                return this.updateRootFileField;
            }
            set {
                this.updateRootFileField = value;
                this.RaisePropertyChanged("UpdateRootFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConferenceVersionWebserviceSoapChannel : ConferenceModel.ConferenceVersionWebservice.ConferenceVersionWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUpDateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUpDateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NeedVersionUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public NeedVersionUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceVersionWebserviceSoapClient : System.ServiceModel.ClientBase<ConferenceModel.ConferenceVersionWebservice.ConferenceVersionWebserviceSoap>, ConferenceModel.ConferenceVersionWebservice.ConferenceVersionWebserviceSoap {
        
        private BeginOperationDelegate onBeginGetUpDateFileDelegate;
        
        private EndOperationDelegate onEndGetUpDateFileDelegate;
        
        private System.Threading.SendOrPostCallback onGetUpDateFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginNeedVersionUpdateDelegate;
        
        private EndOperationDelegate onEndNeedVersionUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onNeedVersionUpdateCompletedDelegate;
        
        public ConferenceVersionWebserviceSoapClient() {
        }
        
        public ConferenceVersionWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceVersionWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceVersionWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceVersionWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetUpDateFileCompletedEventArgs> GetUpDateFileCompleted;
        
        public event System.EventHandler<NeedVersionUpdateCompletedEventArgs> NeedVersionUpdateCompleted;
        
        public ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity GetUpDateFile() {
            return base.Channel.GetUpDateFile();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUpDateFile(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUpDateFile(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity EndGetUpDateFile(System.IAsyncResult result) {
            return base.Channel.EndGetUpDateFile(result);
        }
        
        private System.IAsyncResult OnBeginGetUpDateFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetUpDateFile(callback, asyncState);
        }
        
        private object[] OnEndGetUpDateFile(System.IAsyncResult result) {
            ConferenceModel.ConferenceVersionWebservice.ConferenceVersionUpdateEntity retVal = this.EndGetUpDateFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUpDateFileCompleted(object state) {
            if ((this.GetUpDateFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUpDateFileCompleted(this, new GetUpDateFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUpDateFileAsync() {
            this.GetUpDateFileAsync(null);
        }
        
        public void GetUpDateFileAsync(object userState) {
            if ((this.onBeginGetUpDateFileDelegate == null)) {
                this.onBeginGetUpDateFileDelegate = new BeginOperationDelegate(this.OnBeginGetUpDateFile);
            }
            if ((this.onEndGetUpDateFileDelegate == null)) {
                this.onEndGetUpDateFileDelegate = new EndOperationDelegate(this.OnEndGetUpDateFile);
            }
            if ((this.onGetUpDateFileCompletedDelegate == null)) {
                this.onGetUpDateFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUpDateFileCompleted);
            }
            base.InvokeAsync(this.onBeginGetUpDateFileDelegate, null, this.onEndGetUpDateFileDelegate, this.onGetUpDateFileCompletedDelegate, userState);
        }
        
        public bool NeedVersionUpdate(string PC_Version) {
            return base.Channel.NeedVersionUpdate(PC_Version);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginNeedVersionUpdate(string PC_Version, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNeedVersionUpdate(PC_Version, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndNeedVersionUpdate(System.IAsyncResult result) {
            return base.Channel.EndNeedVersionUpdate(result);
        }
        
        private System.IAsyncResult OnBeginNeedVersionUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string PC_Version = ((string)(inValues[0]));
            return this.BeginNeedVersionUpdate(PC_Version, callback, asyncState);
        }
        
        private object[] OnEndNeedVersionUpdate(System.IAsyncResult result) {
            bool retVal = this.EndNeedVersionUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnNeedVersionUpdateCompleted(object state) {
            if ((this.NeedVersionUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.NeedVersionUpdateCompleted(this, new NeedVersionUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void NeedVersionUpdateAsync(string PC_Version) {
            this.NeedVersionUpdateAsync(PC_Version, null);
        }
        
        public void NeedVersionUpdateAsync(string PC_Version, object userState) {
            if ((this.onBeginNeedVersionUpdateDelegate == null)) {
                this.onBeginNeedVersionUpdateDelegate = new BeginOperationDelegate(this.OnBeginNeedVersionUpdate);
            }
            if ((this.onEndNeedVersionUpdateDelegate == null)) {
                this.onEndNeedVersionUpdateDelegate = new EndOperationDelegate(this.OnEndNeedVersionUpdate);
            }
            if ((this.onNeedVersionUpdateCompletedDelegate == null)) {
                this.onNeedVersionUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNeedVersionUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginNeedVersionUpdateDelegate, new object[] {
                        PC_Version}, this.onEndNeedVersionUpdateDelegate, this.onNeedVersionUpdateCompletedDelegate, userState);
        }
    }
}
