//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceModel.Studiom_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBTQ.org/", ConfigurationName="Studiom_Service.Pro_KnowledgeServiceSoap")]
    public interface Pro_KnowledgeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/MethodInvoke1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase MethodInvoke1(ConferenceModel.Studiom_Service.ControlType1 controlType);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/MethodInvoke1", ReplyAction="*")]
        System.IAsyncResult BeginMethodInvoke1(ConferenceModel.Studiom_Service.ControlType1 controlType, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndMethodInvoke1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/MethodInvoke2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase MethodInvoke2(ConferenceModel.Studiom_Service.ControlType2 controlType);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/MethodInvoke2", ReplyAction="*")]
        System.IAsyncResult BeginMethodInvoke2(ConferenceModel.Studiom_Service.ControlType2 controlType, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndMethodInvoke2(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/DataAll_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase DataAll_Get();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/DataAll_Get", ReplyAction="*")]
        System.IAsyncResult BeginDataAll_Get(System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndDataAll_Get(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/MatrixChange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase MatrixChange(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/MatrixChange", ReplyAction="*")]
        System.IAsyncResult BeginMatrixChange(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndMatrixChange(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/Dispose", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase Dispose();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/Dispose", ReplyAction="*")]
        System.IAsyncResult BeginDispose(System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndDispose(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/OrderCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OrderCheck(string Code);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/OrderCheck", ReplyAction="*")]
        System.IAsyncResult BeginOrderCheck(string Code, System.AsyncCallback callback, object asyncState);
        
        void EndOrderCheck(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTQ.org/Maxtrix_Manage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConferenceModel.Studiom_Service.ReturnDataBase Maxtrix_Manage(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://SBTQ.org/Maxtrix_Manage", ReplyAction="*")]
        System.IAsyncResult BeginMaxtrix_Manage(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.Studiom_Service.ReturnDataBase EndMaxtrix_Manage(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SBTQ.org/")]
    public enum ControlType1 {
        
        /// <remarks/>
        Record_Close,
        
        /// <remarks/>
        Record_Begin,
        
        /// <remarks/>
        Record_End,
        
        /// <remarks/>
        Record_CameraStopRotating,
        
        /// <remarks/>
        Record_Up,
        
        /// <remarks/>
        Record_Down,
        
        /// <remarks/>
        Record_Left,
        
        /// <remarks/>
        Record_Right,
        
        /// <remarks/>
        Record_ZoomEnd,
        
        /// <remarks/>
        Record_ZoomLarger,
        
        /// <remarks/>
        Record_ZoomSmaller,
        
        /// <remarks/>
        Record_ManualOperation,
        
        /// <remarks/>
        Record_AutomaticOperation,
        
        /// <remarks/>
        Record_ChangeToView1,
        
        /// <remarks/>
        Record_ChangeToView2,
        
        /// <remarks/>
        Record_ChangeToView3,
        
        /// <remarks/>
        Record_ChangeToView4,
        
        /// <remarks/>
        Record_ChangeToView5,
        
        /// <remarks/>
        Record_ChangeToView6,
        
        /// <remarks/>
        Record_BackUp1,
        
        /// <remarks/>
        Record_BackUp2,
        
        /// <remarks/>
        Record_BackUp3,
        
        /// <remarks/>
        Record_BackUp4,
        
        /// <remarks/>
        Record_BackUp5,
        
        /// <remarks/>
        Record_BackUp6,
        
        /// <remarks/>
        Relay_Run_Line1,
        
        /// <remarks/>
        Relay_Run_Line2,
        
        /// <remarks/>
        Relay_Run_Line3,
        
        /// <remarks/>
        Relay_Run_Line4,
        
        /// <remarks/>
        Relay_Run_Line5,
        
        /// <remarks/>
        Relay_Run_Line6,
        
        /// <remarks/>
        Relay_Run_Line7,
        
        /// <remarks/>
        Relay_Run_Line8,
        
        /// <remarks/>
        Relay_End_Line1,
        
        /// <remarks/>
        Relay_End_Line2,
        
        /// <remarks/>
        Relay_End_Line3,
        
        /// <remarks/>
        Relay_End_Line4,
        
        /// <remarks/>
        Relay_End_Line5,
        
        /// <remarks/>
        Relay_End_Line6,
        
        /// <remarks/>
        Relay_End_Line7,
        
        /// <remarks/>
        Relay_End_Line8,
        
        /// <remarks/>
        PowerSupply_Run_Line1,
        
        /// <remarks/>
        PowerSupply_Run_Line2,
        
        /// <remarks/>
        PowerSupply_Run_Line3,
        
        /// <remarks/>
        PowerSupply_Run_Line4,
        
        /// <remarks/>
        PowerSupply_Run_Line5,
        
        /// <remarks/>
        PowerSupply_Run_Line6,
        
        /// <remarks/>
        PowerSupply_Run_Line7,
        
        /// <remarks/>
        PowerSupply_Run_Line8,
        
        /// <remarks/>
        PowerSupply_End_Line1,
        
        /// <remarks/>
        PowerSupply_End_Line2,
        
        /// <remarks/>
        PowerSupply_End_Line3,
        
        /// <remarks/>
        PowerSupply_End_Line4,
        
        /// <remarks/>
        PowerSupply_End_Line5,
        
        /// <remarks/>
        PowerSupply_End_Line6,
        
        /// <remarks/>
        PowerSupply_End_Line7,
        
        /// <remarks/>
        PowerSupply_End_Line8,
        
        /// <remarks/>
        PowerSupply_ShutAllLines,
        
        /// <remarks/>
        PC_UP,
        
        /// <remarks/>
        PC_DOWN,
        
        /// <remarks/>
        PC_Stop,
        
        /// <remarks/>
        PC_Before,
        
        /// <remarks/>
        PC_After,
        
        /// <remarks/>
        Relay_RunAllLines,
        
        /// <remarks/>
        Relay_ShutAllLines,
        
        /// <remarks/>
        PowerSupply_RunAllLines,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SBTQ.org/")]
    public partial class ReturnDataBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string methodField;
        
        private string innerErrorField;
        
        private string serverErrorField;
        
        private string return_ParamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
                this.RaisePropertyChanged("Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InnerError {
            get {
                return this.innerErrorField;
            }
            set {
                this.innerErrorField = value;
                this.RaisePropertyChanged("InnerError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServerError {
            get {
                return this.serverErrorField;
            }
            set {
                this.serverErrorField = value;
                this.RaisePropertyChanged("ServerError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Return_Param {
            get {
                return this.return_ParamField;
            }
            set {
                this.return_ParamField = value;
                this.RaisePropertyChanged("Return_Param");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SBTQ.org/")]
    public enum ControlType2 {
        
        /// <remarks/>
        Fan_Open,
        
        /// <remarks/>
        Fan_Close,
        
        /// <remarks/>
        Switch_All_Open,
        
        /// <remarks/>
        Switch_All_Close,
        
        /// <remarks/>
        Certain_Open,
        
        /// <remarks/>
        Certain_Close,
        
        /// <remarks/>
        Alarm_Open,
        
        /// <remarks/>
        Alarm_Close,
        
        /// <remarks/>
        Light_Open,
        
        /// <remarks/>
        Light_Close,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SBTQ.org/")]
    public enum MatrixChangeType {
        
        /// <remarks/>
        OneToOne,
        
        /// <remarks/>
        OneToTwo,
        
        /// <remarks/>
        TwoToOne,
        
        /// <remarks/>
        TwoToTwo,
        
        /// <remarks/>
        ThreeToOne,
        
        /// <remarks/>
        ThreeToTwo,
        
        /// <remarks/>
        FourToOne,
        
        /// <remarks/>
        FourToTwo,
        
        /// <remarks/>
        FiveToOne,
        
        /// <remarks/>
        FiveToTwo,
        
        /// <remarks/>
        SixToOne,
        
        /// <remarks/>
        SixToTwo,
        
        /// <remarks/>
        SevenToOne,
        
        /// <remarks/>
        SevenToTwo,
        
        /// <remarks/>
        EightToOne,
        
        /// <remarks/>
        EightToTwo,
        
        /// <remarks/>
        NineToOne,
        
        /// <remarks/>
        NineToTwo,
        
        /// <remarks/>
        TenToOne,
        
        /// <remarks/>
        TenToTwo,
        
        /// <remarks/>
        ElevenToOne,
        
        /// <remarks/>
        ElevenToTwo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SBTQ.org/")]
    public enum MaxtrixType {
        
        /// <remarks/>
        maxtrix1,
        
        /// <remarks/>
        maxtrix2,
        
        /// <remarks/>
        maxtrix3,
        
        /// <remarks/>
        maxtrix4,
        
        /// <remarks/>
        maxtrix5,
        
        /// <remarks/>
        maxtrix6,
        
        /// <remarks/>
        maxtrix7,
        
        /// <remarks/>
        maxtrix8,
        
        /// <remarks/>
        maxtrix9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Pro_KnowledgeServiceSoapChannel : ConferenceModel.Studiom_Service.Pro_KnowledgeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MethodInvoke1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MethodInvoke1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MethodInvoke2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MethodInvoke2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataAll_GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DataAll_GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatrixChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MatrixChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisposeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DisposeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Maxtrix_ManageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Maxtrix_ManageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.Studiom_Service.ReturnDataBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Pro_KnowledgeServiceSoapClient : System.ServiceModel.ClientBase<ConferenceModel.Studiom_Service.Pro_KnowledgeServiceSoap>, ConferenceModel.Studiom_Service.Pro_KnowledgeServiceSoap {
        
        private BeginOperationDelegate onBeginMethodInvoke1Delegate;
        
        private EndOperationDelegate onEndMethodInvoke1Delegate;
        
        private System.Threading.SendOrPostCallback onMethodInvoke1CompletedDelegate;
        
        private BeginOperationDelegate onBeginMethodInvoke2Delegate;
        
        private EndOperationDelegate onEndMethodInvoke2Delegate;
        
        private System.Threading.SendOrPostCallback onMethodInvoke2CompletedDelegate;
        
        private BeginOperationDelegate onBeginDataAll_GetDelegate;
        
        private EndOperationDelegate onEndDataAll_GetDelegate;
        
        private System.Threading.SendOrPostCallback onDataAll_GetCompletedDelegate;
        
        private BeginOperationDelegate onBeginMatrixChangeDelegate;
        
        private EndOperationDelegate onEndMatrixChangeDelegate;
        
        private System.Threading.SendOrPostCallback onMatrixChangeCompletedDelegate;
        
        private BeginOperationDelegate onBeginDisposeDelegate;
        
        private EndOperationDelegate onEndDisposeDelegate;
        
        private System.Threading.SendOrPostCallback onDisposeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOrderCheckDelegate;
        
        private EndOperationDelegate onEndOrderCheckDelegate;
        
        private System.Threading.SendOrPostCallback onOrderCheckCompletedDelegate;
        
        private BeginOperationDelegate onBeginMaxtrix_ManageDelegate;
        
        private EndOperationDelegate onEndMaxtrix_ManageDelegate;
        
        private System.Threading.SendOrPostCallback onMaxtrix_ManageCompletedDelegate;
        
        public Pro_KnowledgeServiceSoapClient() {
        }
        
        public Pro_KnowledgeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Pro_KnowledgeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pro_KnowledgeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pro_KnowledgeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<MethodInvoke1CompletedEventArgs> MethodInvoke1Completed;
        
        public event System.EventHandler<MethodInvoke2CompletedEventArgs> MethodInvoke2Completed;
        
        public event System.EventHandler<DataAll_GetCompletedEventArgs> DataAll_GetCompleted;
        
        public event System.EventHandler<MatrixChangeCompletedEventArgs> MatrixChangeCompleted;
        
        public event System.EventHandler<DisposeCompletedEventArgs> DisposeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OrderCheckCompleted;
        
        public event System.EventHandler<Maxtrix_ManageCompletedEventArgs> Maxtrix_ManageCompleted;
        
        public ConferenceModel.Studiom_Service.ReturnDataBase MethodInvoke1(ConferenceModel.Studiom_Service.ControlType1 controlType) {
            return base.Channel.MethodInvoke1(controlType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMethodInvoke1(ConferenceModel.Studiom_Service.ControlType1 controlType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMethodInvoke1(controlType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndMethodInvoke1(System.IAsyncResult result) {
            return base.Channel.EndMethodInvoke1(result);
        }
        
        private System.IAsyncResult OnBeginMethodInvoke1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConferenceModel.Studiom_Service.ControlType1 controlType = ((ConferenceModel.Studiom_Service.ControlType1)(inValues[0]));
            return this.BeginMethodInvoke1(controlType, callback, asyncState);
        }
        
        private object[] OnEndMethodInvoke1(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndMethodInvoke1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMethodInvoke1Completed(object state) {
            if ((this.MethodInvoke1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MethodInvoke1Completed(this, new MethodInvoke1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MethodInvoke1Async(ConferenceModel.Studiom_Service.ControlType1 controlType) {
            this.MethodInvoke1Async(controlType, null);
        }
        
        public void MethodInvoke1Async(ConferenceModel.Studiom_Service.ControlType1 controlType, object userState) {
            if ((this.onBeginMethodInvoke1Delegate == null)) {
                this.onBeginMethodInvoke1Delegate = new BeginOperationDelegate(this.OnBeginMethodInvoke1);
            }
            if ((this.onEndMethodInvoke1Delegate == null)) {
                this.onEndMethodInvoke1Delegate = new EndOperationDelegate(this.OnEndMethodInvoke1);
            }
            if ((this.onMethodInvoke1CompletedDelegate == null)) {
                this.onMethodInvoke1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMethodInvoke1Completed);
            }
            base.InvokeAsync(this.onBeginMethodInvoke1Delegate, new object[] {
                        controlType}, this.onEndMethodInvoke1Delegate, this.onMethodInvoke1CompletedDelegate, userState);
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase MethodInvoke2(ConferenceModel.Studiom_Service.ControlType2 controlType) {
            return base.Channel.MethodInvoke2(controlType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMethodInvoke2(ConferenceModel.Studiom_Service.ControlType2 controlType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMethodInvoke2(controlType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndMethodInvoke2(System.IAsyncResult result) {
            return base.Channel.EndMethodInvoke2(result);
        }
        
        private System.IAsyncResult OnBeginMethodInvoke2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConferenceModel.Studiom_Service.ControlType2 controlType = ((ConferenceModel.Studiom_Service.ControlType2)(inValues[0]));
            return this.BeginMethodInvoke2(controlType, callback, asyncState);
        }
        
        private object[] OnEndMethodInvoke2(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndMethodInvoke2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMethodInvoke2Completed(object state) {
            if ((this.MethodInvoke2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MethodInvoke2Completed(this, new MethodInvoke2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MethodInvoke2Async(ConferenceModel.Studiom_Service.ControlType2 controlType) {
            this.MethodInvoke2Async(controlType, null);
        }
        
        public void MethodInvoke2Async(ConferenceModel.Studiom_Service.ControlType2 controlType, object userState) {
            if ((this.onBeginMethodInvoke2Delegate == null)) {
                this.onBeginMethodInvoke2Delegate = new BeginOperationDelegate(this.OnBeginMethodInvoke2);
            }
            if ((this.onEndMethodInvoke2Delegate == null)) {
                this.onEndMethodInvoke2Delegate = new EndOperationDelegate(this.OnEndMethodInvoke2);
            }
            if ((this.onMethodInvoke2CompletedDelegate == null)) {
                this.onMethodInvoke2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMethodInvoke2Completed);
            }
            base.InvokeAsync(this.onBeginMethodInvoke2Delegate, new object[] {
                        controlType}, this.onEndMethodInvoke2Delegate, this.onMethodInvoke2CompletedDelegate, userState);
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase DataAll_Get() {
            return base.Channel.DataAll_Get();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDataAll_Get(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDataAll_Get(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndDataAll_Get(System.IAsyncResult result) {
            return base.Channel.EndDataAll_Get(result);
        }
        
        private System.IAsyncResult OnBeginDataAll_Get(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDataAll_Get(callback, asyncState);
        }
        
        private object[] OnEndDataAll_Get(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndDataAll_Get(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDataAll_GetCompleted(object state) {
            if ((this.DataAll_GetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DataAll_GetCompleted(this, new DataAll_GetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DataAll_GetAsync() {
            this.DataAll_GetAsync(null);
        }
        
        public void DataAll_GetAsync(object userState) {
            if ((this.onBeginDataAll_GetDelegate == null)) {
                this.onBeginDataAll_GetDelegate = new BeginOperationDelegate(this.OnBeginDataAll_Get);
            }
            if ((this.onEndDataAll_GetDelegate == null)) {
                this.onEndDataAll_GetDelegate = new EndOperationDelegate(this.OnEndDataAll_Get);
            }
            if ((this.onDataAll_GetCompletedDelegate == null)) {
                this.onDataAll_GetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDataAll_GetCompleted);
            }
            base.InvokeAsync(this.onBeginDataAll_GetDelegate, null, this.onEndDataAll_GetDelegate, this.onDataAll_GetCompletedDelegate, userState);
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase MatrixChange(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType) {
            return base.Channel.MatrixChange(matrixChangeType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMatrixChange(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMatrixChange(matrixChangeType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndMatrixChange(System.IAsyncResult result) {
            return base.Channel.EndMatrixChange(result);
        }
        
        private System.IAsyncResult OnBeginMatrixChange(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType = ((ConferenceModel.Studiom_Service.MatrixChangeType)(inValues[0]));
            return this.BeginMatrixChange(matrixChangeType, callback, asyncState);
        }
        
        private object[] OnEndMatrixChange(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndMatrixChange(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMatrixChangeCompleted(object state) {
            if ((this.MatrixChangeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MatrixChangeCompleted(this, new MatrixChangeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MatrixChangeAsync(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType) {
            this.MatrixChangeAsync(matrixChangeType, null);
        }
        
        public void MatrixChangeAsync(ConferenceModel.Studiom_Service.MatrixChangeType matrixChangeType, object userState) {
            if ((this.onBeginMatrixChangeDelegate == null)) {
                this.onBeginMatrixChangeDelegate = new BeginOperationDelegate(this.OnBeginMatrixChange);
            }
            if ((this.onEndMatrixChangeDelegate == null)) {
                this.onEndMatrixChangeDelegate = new EndOperationDelegate(this.OnEndMatrixChange);
            }
            if ((this.onMatrixChangeCompletedDelegate == null)) {
                this.onMatrixChangeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMatrixChangeCompleted);
            }
            base.InvokeAsync(this.onBeginMatrixChangeDelegate, new object[] {
                        matrixChangeType}, this.onEndMatrixChangeDelegate, this.onMatrixChangeCompletedDelegate, userState);
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Dispose() {
            return base.Channel.Dispose();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDispose(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDispose(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndDispose(System.IAsyncResult result) {
            return base.Channel.EndDispose(result);
        }
        
        private System.IAsyncResult OnBeginDispose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDispose(callback, asyncState);
        }
        
        private object[] OnEndDispose(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndDispose(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDisposeCompleted(object state) {
            if ((this.DisposeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DisposeCompleted(this, new DisposeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DisposeAsync() {
            this.DisposeAsync(null);
        }
        
        public void DisposeAsync(object userState) {
            if ((this.onBeginDisposeDelegate == null)) {
                this.onBeginDisposeDelegate = new BeginOperationDelegate(this.OnBeginDispose);
            }
            if ((this.onEndDisposeDelegate == null)) {
                this.onEndDisposeDelegate = new EndOperationDelegate(this.OnEndDispose);
            }
            if ((this.onDisposeCompletedDelegate == null)) {
                this.onDisposeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDisposeCompleted);
            }
            base.InvokeAsync(this.onBeginDisposeDelegate, null, this.onEndDisposeDelegate, this.onDisposeCompletedDelegate, userState);
        }
        
        public void OrderCheck(string Code) {
            base.Channel.OrderCheck(Code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginOrderCheck(string Code, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOrderCheck(Code, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndOrderCheck(System.IAsyncResult result) {
            base.Channel.EndOrderCheck(result);
        }
        
        private System.IAsyncResult OnBeginOrderCheck(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Code = ((string)(inValues[0]));
            return this.BeginOrderCheck(Code, callback, asyncState);
        }
        
        private object[] OnEndOrderCheck(System.IAsyncResult result) {
            this.EndOrderCheck(result);
            return null;
        }
        
        private void OnOrderCheckCompleted(object state) {
            if ((this.OrderCheckCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OrderCheckCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OrderCheckAsync(string Code) {
            this.OrderCheckAsync(Code, null);
        }
        
        public void OrderCheckAsync(string Code, object userState) {
            if ((this.onBeginOrderCheckDelegate == null)) {
                this.onBeginOrderCheckDelegate = new BeginOperationDelegate(this.OnBeginOrderCheck);
            }
            if ((this.onEndOrderCheckDelegate == null)) {
                this.onEndOrderCheckDelegate = new EndOperationDelegate(this.OnEndOrderCheck);
            }
            if ((this.onOrderCheckCompletedDelegate == null)) {
                this.onOrderCheckCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOrderCheckCompleted);
            }
            base.InvokeAsync(this.onBeginOrderCheckDelegate, new object[] {
                        Code}, this.onEndOrderCheckDelegate, this.onOrderCheckCompletedDelegate, userState);
        }
        
        public ConferenceModel.Studiom_Service.ReturnDataBase Maxtrix_Manage(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType) {
            return base.Channel.Maxtrix_Manage(maxtrixType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMaxtrix_Manage(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMaxtrix_Manage(maxtrixType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.Studiom_Service.ReturnDataBase EndMaxtrix_Manage(System.IAsyncResult result) {
            return base.Channel.EndMaxtrix_Manage(result);
        }
        
        private System.IAsyncResult OnBeginMaxtrix_Manage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConferenceModel.Studiom_Service.MaxtrixType maxtrixType = ((ConferenceModel.Studiom_Service.MaxtrixType)(inValues[0]));
            return this.BeginMaxtrix_Manage(maxtrixType, callback, asyncState);
        }
        
        private object[] OnEndMaxtrix_Manage(System.IAsyncResult result) {
            ConferenceModel.Studiom_Service.ReturnDataBase retVal = this.EndMaxtrix_Manage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMaxtrix_ManageCompleted(object state) {
            if ((this.Maxtrix_ManageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Maxtrix_ManageCompleted(this, new Maxtrix_ManageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Maxtrix_ManageAsync(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType) {
            this.Maxtrix_ManageAsync(maxtrixType, null);
        }
        
        public void Maxtrix_ManageAsync(ConferenceModel.Studiom_Service.MaxtrixType maxtrixType, object userState) {
            if ((this.onBeginMaxtrix_ManageDelegate == null)) {
                this.onBeginMaxtrix_ManageDelegate = new BeginOperationDelegate(this.OnBeginMaxtrix_Manage);
            }
            if ((this.onEndMaxtrix_ManageDelegate == null)) {
                this.onEndMaxtrix_ManageDelegate = new EndOperationDelegate(this.OnEndMaxtrix_Manage);
            }
            if ((this.onMaxtrix_ManageCompletedDelegate == null)) {
                this.onMaxtrix_ManageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMaxtrix_ManageCompleted);
            }
            base.InvokeAsync(this.onBeginMaxtrix_ManageDelegate, new object[] {
                        maxtrixType}, this.onEndMaxtrix_ManageDelegate, this.onMaxtrix_ManageCompletedDelegate, userState);
        }
    }
}
