//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceModel.ConferenceLyncConversationWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConferenceLyncConversationWebservice.ConferenceLyncConversationWebserviceSoap")]
    public interface ConferenceLyncConversationWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JoinConferenceMainLyncConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void JoinConferenceMainLyncConversation(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/JoinConferenceMainLyncConversation", ReplyAction="*")]
        System.IAsyncResult BeginJoinConferenceMainLyncConversation(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity, System.AsyncCallback callback, object asyncState);
        
        void EndJoinConferenceMainLyncConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterBigScreen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void InterBigScreen(int conferenceID, string sharer);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterBigScreen", ReplyAction="*")]
        System.IAsyncResult BeginInterBigScreen(int conferenceID, string sharer, System.AsyncCallback callback, object asyncState);
        
        void EndInterBigScreen(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPTControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void PPTControl(int conferenceID, string controler);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PPTControl", ReplyAction="*")]
        System.IAsyncResult BeginPPTControl(int conferenceID, string controler, System.AsyncCallback callback, object asyncState);
        
        void EndPPTControl(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContainConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        string ContainConversation(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ContainConversation", ReplyAction="*")]
        System.IAsyncResult BeginContainConversation(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        string EndContainConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void FillConversation(int conferenceID, string meetAddress);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FillConversation", ReplyAction="*")]
        System.IAsyncResult BeginFillConversation(int conferenceID, string meetAddress, System.AsyncCallback callback, object asyncState);
        
        void EndFillConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForceRemoveConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void ForceRemoveConversation(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ForceRemoveConversation", ReplyAction="*")]
        System.IAsyncResult BeginForceRemoveConversation(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        void EndForceRemoveConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void RemoveConversation(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RemoveConversation", ReplyAction="*")]
        System.IAsyncResult BeginRemoveConversation(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        void EndRemoveConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeaveConversation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void LeaveConversation(int conferenceID, string contactUri);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeaveConversation", ReplyAction="*")]
        System.IAsyncResult BeginLeaveConversation(int conferenceID, string contactUri, System.AsyncCallback callback, object asyncState);
        
        void EndLeaveConversation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForbiddenConversationInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void ForbiddenConversationInit(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ForbiddenConversationInit", ReplyAction="*")]
        System.IAsyncResult BeginForbiddenConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        void EndForbiddenConversationInit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllowConversationInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void AllowConversationInit(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AllowConversationInit", ReplyAction="*")]
        System.IAsyncResult BeginAllowConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        void EndAllowConversationInit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckConversationInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        bool CheckConversationInit(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CheckConversationInit", ReplyAction="*")]
        System.IAsyncResult BeginCheckConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        bool EndCheckConversationInit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShareApplicationResourceNotify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LyncEntityBase))]
        void ShareApplicationResourceNotify(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ShareApplicationResourceNotify", ReplyAction="*")]
        System.IAsyncResult BeginShareApplicationResourceNotify(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify, System.AsyncCallback callback, object asyncState);
        
        void EndShareApplicationResourceNotify(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LyncConversationEntity : LyncEntityBase {
        
        private string jonConferencePersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JonConferencePerson {
            get {
                return this.jonConferencePersonField;
            }
            set {
                this.jonConferencePersonField = value;
                this.RaisePropertyChanged("JonConferencePerson");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LyncResourceNotify))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LyncConversationEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LyncEntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LyncResourceNotify : LyncEntityBase {
        
        private string resourceShareNameField;
        
        private string resourceSharePersonNameField;
        
        private string resourceSharePersonUriField;
        
        private LyncResourceOperationCodeType lyncResourceOperationCodeTypeField;
        
        private ResourceType resourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResourceShareName {
            get {
                return this.resourceShareNameField;
            }
            set {
                this.resourceShareNameField = value;
                this.RaisePropertyChanged("ResourceShareName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResourceSharePersonName {
            get {
                return this.resourceSharePersonNameField;
            }
            set {
                this.resourceSharePersonNameField = value;
                this.RaisePropertyChanged("ResourceSharePersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResourceSharePersonUri {
            get {
                return this.resourceSharePersonUriField;
            }
            set {
                this.resourceSharePersonUriField = value;
                this.RaisePropertyChanged("ResourceSharePersonUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LyncResourceOperationCodeType LyncResourceOperationCodeType {
            get {
                return this.lyncResourceOperationCodeTypeField;
            }
            set {
                this.lyncResourceOperationCodeTypeField = value;
                this.RaisePropertyChanged("LyncResourceOperationCodeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ResourceType ResourceType {
            get {
                return this.resourceTypeField;
            }
            set {
                this.resourceTypeField = value;
                this.RaisePropertyChanged("ResourceType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LyncResourceOperationCodeType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        ShareResource,
        
        /// <remarks/>
        ExitShareResource,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ResourceType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        DeskTop,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConferenceLyncConversationWebserviceSoapChannel : ConferenceModel.ConferenceLyncConversationWebservice.ConferenceLyncConversationWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContainConversationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ContainConversationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckConversationInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckConversationInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceLyncConversationWebserviceSoapClient : System.ServiceModel.ClientBase<ConferenceModel.ConferenceLyncConversationWebservice.ConferenceLyncConversationWebserviceSoap>, ConferenceModel.ConferenceLyncConversationWebservice.ConferenceLyncConversationWebserviceSoap {
        
        private BeginOperationDelegate onBeginJoinConferenceMainLyncConversationDelegate;
        
        private EndOperationDelegate onEndJoinConferenceMainLyncConversationDelegate;
        
        private System.Threading.SendOrPostCallback onJoinConferenceMainLyncConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginInterBigScreenDelegate;
        
        private EndOperationDelegate onEndInterBigScreenDelegate;
        
        private System.Threading.SendOrPostCallback onInterBigScreenCompletedDelegate;
        
        private BeginOperationDelegate onBeginPPTControlDelegate;
        
        private EndOperationDelegate onEndPPTControlDelegate;
        
        private System.Threading.SendOrPostCallback onPPTControlCompletedDelegate;
        
        private BeginOperationDelegate onBeginContainConversationDelegate;
        
        private EndOperationDelegate onEndContainConversationDelegate;
        
        private System.Threading.SendOrPostCallback onContainConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginFillConversationDelegate;
        
        private EndOperationDelegate onEndFillConversationDelegate;
        
        private System.Threading.SendOrPostCallback onFillConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginForceRemoveConversationDelegate;
        
        private EndOperationDelegate onEndForceRemoveConversationDelegate;
        
        private System.Threading.SendOrPostCallback onForceRemoveConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveConversationDelegate;
        
        private EndOperationDelegate onEndRemoveConversationDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginLeaveConversationDelegate;
        
        private EndOperationDelegate onEndLeaveConversationDelegate;
        
        private System.Threading.SendOrPostCallback onLeaveConversationCompletedDelegate;
        
        private BeginOperationDelegate onBeginForbiddenConversationInitDelegate;
        
        private EndOperationDelegate onEndForbiddenConversationInitDelegate;
        
        private System.Threading.SendOrPostCallback onForbiddenConversationInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginAllowConversationInitDelegate;
        
        private EndOperationDelegate onEndAllowConversationInitDelegate;
        
        private System.Threading.SendOrPostCallback onAllowConversationInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckConversationInitDelegate;
        
        private EndOperationDelegate onEndCheckConversationInitDelegate;
        
        private System.Threading.SendOrPostCallback onCheckConversationInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginShareApplicationResourceNotifyDelegate;
        
        private EndOperationDelegate onEndShareApplicationResourceNotifyDelegate;
        
        private System.Threading.SendOrPostCallback onShareApplicationResourceNotifyCompletedDelegate;
        
        public ConferenceLyncConversationWebserviceSoapClient() {
        }
        
        public ConferenceLyncConversationWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceLyncConversationWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceLyncConversationWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceLyncConversationWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> JoinConferenceMainLyncConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InterBigScreenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PPTControlCompleted;
        
        public event System.EventHandler<ContainConversationCompletedEventArgs> ContainConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> FillConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ForceRemoveConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RemoveConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LeaveConversationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ForbiddenConversationInitCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AllowConversationInitCompleted;
        
        public event System.EventHandler<CheckConversationInitCompletedEventArgs> CheckConversationInitCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ShareApplicationResourceNotifyCompleted;
        
        public void JoinConferenceMainLyncConversation(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity) {
            base.Channel.JoinConferenceMainLyncConversation(conferenceID, lyncConversationEntity);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginJoinConferenceMainLyncConversation(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginJoinConferenceMainLyncConversation(conferenceID, lyncConversationEntity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndJoinConferenceMainLyncConversation(System.IAsyncResult result) {
            base.Channel.EndJoinConferenceMainLyncConversation(result);
        }
        
        private System.IAsyncResult OnBeginJoinConferenceMainLyncConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity = ((ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity)(inValues[1]));
            return this.BeginJoinConferenceMainLyncConversation(conferenceID, lyncConversationEntity, callback, asyncState);
        }
        
        private object[] OnEndJoinConferenceMainLyncConversation(System.IAsyncResult result) {
            this.EndJoinConferenceMainLyncConversation(result);
            return null;
        }
        
        private void OnJoinConferenceMainLyncConversationCompleted(object state) {
            if ((this.JoinConferenceMainLyncConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.JoinConferenceMainLyncConversationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void JoinConferenceMainLyncConversationAsync(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity) {
            this.JoinConferenceMainLyncConversationAsync(conferenceID, lyncConversationEntity, null);
        }
        
        public void JoinConferenceMainLyncConversationAsync(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncConversationEntity lyncConversationEntity, object userState) {
            if ((this.onBeginJoinConferenceMainLyncConversationDelegate == null)) {
                this.onBeginJoinConferenceMainLyncConversationDelegate = new BeginOperationDelegate(this.OnBeginJoinConferenceMainLyncConversation);
            }
            if ((this.onEndJoinConferenceMainLyncConversationDelegate == null)) {
                this.onEndJoinConferenceMainLyncConversationDelegate = new EndOperationDelegate(this.OnEndJoinConferenceMainLyncConversation);
            }
            if ((this.onJoinConferenceMainLyncConversationCompletedDelegate == null)) {
                this.onJoinConferenceMainLyncConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnJoinConferenceMainLyncConversationCompleted);
            }
            base.InvokeAsync(this.onBeginJoinConferenceMainLyncConversationDelegate, new object[] {
                        conferenceID,
                        lyncConversationEntity}, this.onEndJoinConferenceMainLyncConversationDelegate, this.onJoinConferenceMainLyncConversationCompletedDelegate, userState);
        }
        
        public void InterBigScreen(int conferenceID, string sharer) {
            base.Channel.InterBigScreen(conferenceID, sharer);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInterBigScreen(int conferenceID, string sharer, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInterBigScreen(conferenceID, sharer, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndInterBigScreen(System.IAsyncResult result) {
            base.Channel.EndInterBigScreen(result);
        }
        
        private System.IAsyncResult OnBeginInterBigScreen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string sharer = ((string)(inValues[1]));
            return this.BeginInterBigScreen(conferenceID, sharer, callback, asyncState);
        }
        
        private object[] OnEndInterBigScreen(System.IAsyncResult result) {
            this.EndInterBigScreen(result);
            return null;
        }
        
        private void OnInterBigScreenCompleted(object state) {
            if ((this.InterBigScreenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InterBigScreenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InterBigScreenAsync(int conferenceID, string sharer) {
            this.InterBigScreenAsync(conferenceID, sharer, null);
        }
        
        public void InterBigScreenAsync(int conferenceID, string sharer, object userState) {
            if ((this.onBeginInterBigScreenDelegate == null)) {
                this.onBeginInterBigScreenDelegate = new BeginOperationDelegate(this.OnBeginInterBigScreen);
            }
            if ((this.onEndInterBigScreenDelegate == null)) {
                this.onEndInterBigScreenDelegate = new EndOperationDelegate(this.OnEndInterBigScreen);
            }
            if ((this.onInterBigScreenCompletedDelegate == null)) {
                this.onInterBigScreenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInterBigScreenCompleted);
            }
            base.InvokeAsync(this.onBeginInterBigScreenDelegate, new object[] {
                        conferenceID,
                        sharer}, this.onEndInterBigScreenDelegate, this.onInterBigScreenCompletedDelegate, userState);
        }
        
        public void PPTControl(int conferenceID, string controler) {
            base.Channel.PPTControl(conferenceID, controler);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPPTControl(int conferenceID, string controler, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPPTControl(conferenceID, controler, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndPPTControl(System.IAsyncResult result) {
            base.Channel.EndPPTControl(result);
        }
        
        private System.IAsyncResult OnBeginPPTControl(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string controler = ((string)(inValues[1]));
            return this.BeginPPTControl(conferenceID, controler, callback, asyncState);
        }
        
        private object[] OnEndPPTControl(System.IAsyncResult result) {
            this.EndPPTControl(result);
            return null;
        }
        
        private void OnPPTControlCompleted(object state) {
            if ((this.PPTControlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PPTControlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PPTControlAsync(int conferenceID, string controler) {
            this.PPTControlAsync(conferenceID, controler, null);
        }
        
        public void PPTControlAsync(int conferenceID, string controler, object userState) {
            if ((this.onBeginPPTControlDelegate == null)) {
                this.onBeginPPTControlDelegate = new BeginOperationDelegate(this.OnBeginPPTControl);
            }
            if ((this.onEndPPTControlDelegate == null)) {
                this.onEndPPTControlDelegate = new EndOperationDelegate(this.OnEndPPTControl);
            }
            if ((this.onPPTControlCompletedDelegate == null)) {
                this.onPPTControlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPPTControlCompleted);
            }
            base.InvokeAsync(this.onBeginPPTControlDelegate, new object[] {
                        conferenceID,
                        controler}, this.onEndPPTControlDelegate, this.onPPTControlCompletedDelegate, userState);
        }
        
        public string ContainConversation(int conferenceID) {
            return base.Channel.ContainConversation(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginContainConversation(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContainConversation(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndContainConversation(System.IAsyncResult result) {
            return base.Channel.EndContainConversation(result);
        }
        
        private System.IAsyncResult OnBeginContainConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginContainConversation(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndContainConversation(System.IAsyncResult result) {
            string retVal = this.EndContainConversation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnContainConversationCompleted(object state) {
            if ((this.ContainConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContainConversationCompleted(this, new ContainConversationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContainConversationAsync(int conferenceID) {
            this.ContainConversationAsync(conferenceID, null);
        }
        
        public void ContainConversationAsync(int conferenceID, object userState) {
            if ((this.onBeginContainConversationDelegate == null)) {
                this.onBeginContainConversationDelegate = new BeginOperationDelegate(this.OnBeginContainConversation);
            }
            if ((this.onEndContainConversationDelegate == null)) {
                this.onEndContainConversationDelegate = new EndOperationDelegate(this.OnEndContainConversation);
            }
            if ((this.onContainConversationCompletedDelegate == null)) {
                this.onContainConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContainConversationCompleted);
            }
            base.InvokeAsync(this.onBeginContainConversationDelegate, new object[] {
                        conferenceID}, this.onEndContainConversationDelegate, this.onContainConversationCompletedDelegate, userState);
        }
        
        public void FillConversation(int conferenceID, string meetAddress) {
            base.Channel.FillConversation(conferenceID, meetAddress);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFillConversation(int conferenceID, string meetAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFillConversation(conferenceID, meetAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndFillConversation(System.IAsyncResult result) {
            base.Channel.EndFillConversation(result);
        }
        
        private System.IAsyncResult OnBeginFillConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string meetAddress = ((string)(inValues[1]));
            return this.BeginFillConversation(conferenceID, meetAddress, callback, asyncState);
        }
        
        private object[] OnEndFillConversation(System.IAsyncResult result) {
            this.EndFillConversation(result);
            return null;
        }
        
        private void OnFillConversationCompleted(object state) {
            if ((this.FillConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FillConversationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FillConversationAsync(int conferenceID, string meetAddress) {
            this.FillConversationAsync(conferenceID, meetAddress, null);
        }
        
        public void FillConversationAsync(int conferenceID, string meetAddress, object userState) {
            if ((this.onBeginFillConversationDelegate == null)) {
                this.onBeginFillConversationDelegate = new BeginOperationDelegate(this.OnBeginFillConversation);
            }
            if ((this.onEndFillConversationDelegate == null)) {
                this.onEndFillConversationDelegate = new EndOperationDelegate(this.OnEndFillConversation);
            }
            if ((this.onFillConversationCompletedDelegate == null)) {
                this.onFillConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFillConversationCompleted);
            }
            base.InvokeAsync(this.onBeginFillConversationDelegate, new object[] {
                        conferenceID,
                        meetAddress}, this.onEndFillConversationDelegate, this.onFillConversationCompletedDelegate, userState);
        }
        
        public void ForceRemoveConversation(int conferenceID) {
            base.Channel.ForceRemoveConversation(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginForceRemoveConversation(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginForceRemoveConversation(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndForceRemoveConversation(System.IAsyncResult result) {
            base.Channel.EndForceRemoveConversation(result);
        }
        
        private System.IAsyncResult OnBeginForceRemoveConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginForceRemoveConversation(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndForceRemoveConversation(System.IAsyncResult result) {
            this.EndForceRemoveConversation(result);
            return null;
        }
        
        private void OnForceRemoveConversationCompleted(object state) {
            if ((this.ForceRemoveConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ForceRemoveConversationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ForceRemoveConversationAsync(int conferenceID) {
            this.ForceRemoveConversationAsync(conferenceID, null);
        }
        
        public void ForceRemoveConversationAsync(int conferenceID, object userState) {
            if ((this.onBeginForceRemoveConversationDelegate == null)) {
                this.onBeginForceRemoveConversationDelegate = new BeginOperationDelegate(this.OnBeginForceRemoveConversation);
            }
            if ((this.onEndForceRemoveConversationDelegate == null)) {
                this.onEndForceRemoveConversationDelegate = new EndOperationDelegate(this.OnEndForceRemoveConversation);
            }
            if ((this.onForceRemoveConversationCompletedDelegate == null)) {
                this.onForceRemoveConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnForceRemoveConversationCompleted);
            }
            base.InvokeAsync(this.onBeginForceRemoveConversationDelegate, new object[] {
                        conferenceID}, this.onEndForceRemoveConversationDelegate, this.onForceRemoveConversationCompletedDelegate, userState);
        }
        
        public void RemoveConversation(int conferenceID) {
            base.Channel.RemoveConversation(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRemoveConversation(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveConversation(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndRemoveConversation(System.IAsyncResult result) {
            base.Channel.EndRemoveConversation(result);
        }
        
        private System.IAsyncResult OnBeginRemoveConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginRemoveConversation(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndRemoveConversation(System.IAsyncResult result) {
            this.EndRemoveConversation(result);
            return null;
        }
        
        private void OnRemoveConversationCompleted(object state) {
            if ((this.RemoveConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveConversationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveConversationAsync(int conferenceID) {
            this.RemoveConversationAsync(conferenceID, null);
        }
        
        public void RemoveConversationAsync(int conferenceID, object userState) {
            if ((this.onBeginRemoveConversationDelegate == null)) {
                this.onBeginRemoveConversationDelegate = new BeginOperationDelegate(this.OnBeginRemoveConversation);
            }
            if ((this.onEndRemoveConversationDelegate == null)) {
                this.onEndRemoveConversationDelegate = new EndOperationDelegate(this.OnEndRemoveConversation);
            }
            if ((this.onRemoveConversationCompletedDelegate == null)) {
                this.onRemoveConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveConversationCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveConversationDelegate, new object[] {
                        conferenceID}, this.onEndRemoveConversationDelegate, this.onRemoveConversationCompletedDelegate, userState);
        }
        
        public void LeaveConversation(int conferenceID, string contactUri) {
            base.Channel.LeaveConversation(conferenceID, contactUri);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLeaveConversation(int conferenceID, string contactUri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLeaveConversation(conferenceID, contactUri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLeaveConversation(System.IAsyncResult result) {
            base.Channel.EndLeaveConversation(result);
        }
        
        private System.IAsyncResult OnBeginLeaveConversation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string contactUri = ((string)(inValues[1]));
            return this.BeginLeaveConversation(conferenceID, contactUri, callback, asyncState);
        }
        
        private object[] OnEndLeaveConversation(System.IAsyncResult result) {
            this.EndLeaveConversation(result);
            return null;
        }
        
        private void OnLeaveConversationCompleted(object state) {
            if ((this.LeaveConversationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LeaveConversationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LeaveConversationAsync(int conferenceID, string contactUri) {
            this.LeaveConversationAsync(conferenceID, contactUri, null);
        }
        
        public void LeaveConversationAsync(int conferenceID, string contactUri, object userState) {
            if ((this.onBeginLeaveConversationDelegate == null)) {
                this.onBeginLeaveConversationDelegate = new BeginOperationDelegate(this.OnBeginLeaveConversation);
            }
            if ((this.onEndLeaveConversationDelegate == null)) {
                this.onEndLeaveConversationDelegate = new EndOperationDelegate(this.OnEndLeaveConversation);
            }
            if ((this.onLeaveConversationCompletedDelegate == null)) {
                this.onLeaveConversationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLeaveConversationCompleted);
            }
            base.InvokeAsync(this.onBeginLeaveConversationDelegate, new object[] {
                        conferenceID,
                        contactUri}, this.onEndLeaveConversationDelegate, this.onLeaveConversationCompletedDelegate, userState);
        }
        
        public void ForbiddenConversationInit(int conferenceID) {
            base.Channel.ForbiddenConversationInit(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginForbiddenConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginForbiddenConversationInit(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndForbiddenConversationInit(System.IAsyncResult result) {
            base.Channel.EndForbiddenConversationInit(result);
        }
        
        private System.IAsyncResult OnBeginForbiddenConversationInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginForbiddenConversationInit(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndForbiddenConversationInit(System.IAsyncResult result) {
            this.EndForbiddenConversationInit(result);
            return null;
        }
        
        private void OnForbiddenConversationInitCompleted(object state) {
            if ((this.ForbiddenConversationInitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ForbiddenConversationInitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ForbiddenConversationInitAsync(int conferenceID) {
            this.ForbiddenConversationInitAsync(conferenceID, null);
        }
        
        public void ForbiddenConversationInitAsync(int conferenceID, object userState) {
            if ((this.onBeginForbiddenConversationInitDelegate == null)) {
                this.onBeginForbiddenConversationInitDelegate = new BeginOperationDelegate(this.OnBeginForbiddenConversationInit);
            }
            if ((this.onEndForbiddenConversationInitDelegate == null)) {
                this.onEndForbiddenConversationInitDelegate = new EndOperationDelegate(this.OnEndForbiddenConversationInit);
            }
            if ((this.onForbiddenConversationInitCompletedDelegate == null)) {
                this.onForbiddenConversationInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnForbiddenConversationInitCompleted);
            }
            base.InvokeAsync(this.onBeginForbiddenConversationInitDelegate, new object[] {
                        conferenceID}, this.onEndForbiddenConversationInitDelegate, this.onForbiddenConversationInitCompletedDelegate, userState);
        }
        
        public void AllowConversationInit(int conferenceID) {
            base.Channel.AllowConversationInit(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAllowConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAllowConversationInit(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAllowConversationInit(System.IAsyncResult result) {
            base.Channel.EndAllowConversationInit(result);
        }
        
        private System.IAsyncResult OnBeginAllowConversationInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginAllowConversationInit(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndAllowConversationInit(System.IAsyncResult result) {
            this.EndAllowConversationInit(result);
            return null;
        }
        
        private void OnAllowConversationInitCompleted(object state) {
            if ((this.AllowConversationInitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AllowConversationInitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AllowConversationInitAsync(int conferenceID) {
            this.AllowConversationInitAsync(conferenceID, null);
        }
        
        public void AllowConversationInitAsync(int conferenceID, object userState) {
            if ((this.onBeginAllowConversationInitDelegate == null)) {
                this.onBeginAllowConversationInitDelegate = new BeginOperationDelegate(this.OnBeginAllowConversationInit);
            }
            if ((this.onEndAllowConversationInitDelegate == null)) {
                this.onEndAllowConversationInitDelegate = new EndOperationDelegate(this.OnEndAllowConversationInit);
            }
            if ((this.onAllowConversationInitCompletedDelegate == null)) {
                this.onAllowConversationInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAllowConversationInitCompleted);
            }
            base.InvokeAsync(this.onBeginAllowConversationInitDelegate, new object[] {
                        conferenceID}, this.onEndAllowConversationInitDelegate, this.onAllowConversationInitCompletedDelegate, userState);
        }
        
        public bool CheckConversationInit(int conferenceID) {
            return base.Channel.CheckConversationInit(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCheckConversationInit(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckConversationInit(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCheckConversationInit(System.IAsyncResult result) {
            return base.Channel.EndCheckConversationInit(result);
        }
        
        private System.IAsyncResult OnBeginCheckConversationInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginCheckConversationInit(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndCheckConversationInit(System.IAsyncResult result) {
            bool retVal = this.EndCheckConversationInit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckConversationInitCompleted(object state) {
            if ((this.CheckConversationInitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckConversationInitCompleted(this, new CheckConversationInitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckConversationInitAsync(int conferenceID) {
            this.CheckConversationInitAsync(conferenceID, null);
        }
        
        public void CheckConversationInitAsync(int conferenceID, object userState) {
            if ((this.onBeginCheckConversationInitDelegate == null)) {
                this.onBeginCheckConversationInitDelegate = new BeginOperationDelegate(this.OnBeginCheckConversationInit);
            }
            if ((this.onEndCheckConversationInitDelegate == null)) {
                this.onEndCheckConversationInitDelegate = new EndOperationDelegate(this.OnEndCheckConversationInit);
            }
            if ((this.onCheckConversationInitCompletedDelegate == null)) {
                this.onCheckConversationInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckConversationInitCompleted);
            }
            base.InvokeAsync(this.onBeginCheckConversationInitDelegate, new object[] {
                        conferenceID}, this.onEndCheckConversationInitDelegate, this.onCheckConversationInitCompletedDelegate, userState);
        }
        
        public void ShareApplicationResourceNotify(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify) {
            base.Channel.ShareApplicationResourceNotify(conferenceID, lyncResourceNotify);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginShareApplicationResourceNotify(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginShareApplicationResourceNotify(conferenceID, lyncResourceNotify, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndShareApplicationResourceNotify(System.IAsyncResult result) {
            base.Channel.EndShareApplicationResourceNotify(result);
        }
        
        private System.IAsyncResult OnBeginShareApplicationResourceNotify(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify = ((ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify)(inValues[1]));
            return this.BeginShareApplicationResourceNotify(conferenceID, lyncResourceNotify, callback, asyncState);
        }
        
        private object[] OnEndShareApplicationResourceNotify(System.IAsyncResult result) {
            this.EndShareApplicationResourceNotify(result);
            return null;
        }
        
        private void OnShareApplicationResourceNotifyCompleted(object state) {
            if ((this.ShareApplicationResourceNotifyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ShareApplicationResourceNotifyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ShareApplicationResourceNotifyAsync(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify) {
            this.ShareApplicationResourceNotifyAsync(conferenceID, lyncResourceNotify, null);
        }
        
        public void ShareApplicationResourceNotifyAsync(int conferenceID, ConferenceModel.ConferenceLyncConversationWebservice.LyncResourceNotify lyncResourceNotify, object userState) {
            if ((this.onBeginShareApplicationResourceNotifyDelegate == null)) {
                this.onBeginShareApplicationResourceNotifyDelegate = new BeginOperationDelegate(this.OnBeginShareApplicationResourceNotify);
            }
            if ((this.onEndShareApplicationResourceNotifyDelegate == null)) {
                this.onEndShareApplicationResourceNotifyDelegate = new EndOperationDelegate(this.OnEndShareApplicationResourceNotify);
            }
            if ((this.onShareApplicationResourceNotifyCompletedDelegate == null)) {
                this.onShareApplicationResourceNotifyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnShareApplicationResourceNotifyCompleted);
            }
            base.InvokeAsync(this.onBeginShareApplicationResourceNotifyDelegate, new object[] {
                        conferenceID,
                        lyncResourceNotify}, this.onEndShareApplicationResourceNotifyDelegate, this.onShareApplicationResourceNotifyCompletedDelegate, userState);
        }
    }
}
