//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceModel.ConferenceMatrixWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConferenceMatrixWebservice.ConferenceMatrixWebserviceSoap")]
    public interface ConferenceMatrixWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMatrixEntity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        void SetMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SetMatrixEntity", ReplyAction="*")]
        System.IAsyncResult BeginSetMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity, System.AsyncCallback callback, object asyncState);
        
        void EndSetMatrixEntity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatrixEntity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity GetMatrixEntity(int conferenceID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetMatrixEntity", ReplyAction="*")]
        System.IAsyncResult BeginGetMatrixEntity(int conferenceID, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity EndGetMatrixEntity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyMatrixEntity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        void ApplyMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ApplyMatrixEntity", ReplyAction="*")]
        System.IAsyncResult BeginApplyMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity, System.AsyncCallback callback, object asyncState);
        
        void EndApplyMatrixEntity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMaxtrixControlCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        void SendMaxtrixControlCode(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SendMaxtrixControlCode", ReplyAction="*")]
        System.IAsyncResult BeginSendMaxtrixControlCode(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode, System.AsyncCallback callback, object asyncState);
        
        void EndSendMaxtrixControlCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InToOneSeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] InToOneSeat(int conferenceID, string seatList, string selfUri, string selfName, string selfIP);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InToOneSeat", ReplyAction="*")]
        System.IAsyncResult BeginInToOneSeat(int conferenceID, string seatList, string selfUri, string selfName, string selfIP, System.AsyncCallback callback, object asyncState);
        
        ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] EndInToOneSeat(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeaveOneSeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConferenceMatrixBase))]
        void LeaveOneSeat(int conferenceID, string selfName, string selfIP);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeaveOneSeat", ReplyAction="*")]
        System.IAsyncResult BeginLeaveOneSeat(int conferenceID, string selfName, string selfIP, System.AsyncCallback callback, object asyncState);
        
        void EndLeaveOneSeat(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConferenceMatrixEntity : ConferenceMatrixBase {
        
        private string sharerField;
        
        private string sharerUriField;
        
        private bool isOnlineField;
        
        private ConferenceMatrixOutPut conferenceMatrixOutPutField;
        
        private SeatEntity seatEntityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sharer {
            get {
                return this.sharerField;
            }
            set {
                this.sharerField = value;
                this.RaisePropertyChanged("Sharer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SharerUri {
            get {
                return this.sharerUriField;
            }
            set {
                this.sharerUriField = value;
                this.RaisePropertyChanged("SharerUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsOnline {
            get {
                return this.isOnlineField;
            }
            set {
                this.isOnlineField = value;
                this.RaisePropertyChanged("IsOnline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ConferenceMatrixOutPut ConferenceMatrixOutPut {
            get {
                return this.conferenceMatrixOutPutField;
            }
            set {
                this.conferenceMatrixOutPutField = value;
                this.RaisePropertyChanged("ConferenceMatrixOutPut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SeatEntity SeatEntity {
            get {
                return this.seatEntityField;
            }
            set {
                this.seatEntityField = value;
                this.RaisePropertyChanged("SeatEntity");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ConferenceMatrixOutPut {
        
        /// <remarks/>
        OutPut1,
        
        /// <remarks/>
        OutPut2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SeatEntity : ConferenceMatrixBase {
        
        private string settingIPField;
        
        private int settingNummberField;
        
        private string userNameField;
        
        private string sharerUriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SettingIP {
            get {
                return this.settingIPField;
            }
            set {
                this.settingIPField = value;
                this.RaisePropertyChanged("SettingIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SettingNummber {
            get {
                return this.settingNummberField;
            }
            set {
                this.settingNummberField = value;
                this.RaisePropertyChanged("SettingNummber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SharerUri {
            get {
                return this.sharerUriField;
            }
            set {
                this.sharerUriField = value;
                this.RaisePropertyChanged("SharerUri");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConferenceMatrixThrowCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConferenceMaxtrixApplyEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SeatEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConferenceMatrixEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConferenceMatrixBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConferenceMatrixThrowCode : ConferenceMatrixBase {
        
        private MatrixThrowCodeType matrixThrowCodeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MatrixThrowCodeType matrixThrowCodeType {
            get {
                return this.matrixThrowCodeTypeField;
            }
            set {
                this.matrixThrowCodeTypeField = value;
                this.RaisePropertyChanged("matrixThrowCodeType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MatrixThrowCodeType {
        
        /// <remarks/>
        ClearProjectionState,
        
        /// <remarks/>
        ClearProjectionTip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConferenceMaxtrixApplyEntity : ConferenceMatrixBase {
        
        private string applyPeopleField;
        
        private ConferenceMatrixOutPut conferenceMatrixOutPutField;
        
        private SeatEntity beforeSeatEntityField;
        
        private SeatEntity seatEntityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplyPeople {
            get {
                return this.applyPeopleField;
            }
            set {
                this.applyPeopleField = value;
                this.RaisePropertyChanged("ApplyPeople");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConferenceMatrixOutPut ConferenceMatrixOutPut {
            get {
                return this.conferenceMatrixOutPutField;
            }
            set {
                this.conferenceMatrixOutPutField = value;
                this.RaisePropertyChanged("ConferenceMatrixOutPut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SeatEntity BeforeSeatEntity {
            get {
                return this.beforeSeatEntityField;
            }
            set {
                this.beforeSeatEntityField = value;
                this.RaisePropertyChanged("BeforeSeatEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SeatEntity SeatEntity {
            get {
                return this.seatEntityField;
            }
            set {
                this.seatEntityField = value;
                this.RaisePropertyChanged("SeatEntity");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConferenceMatrixWebserviceSoapChannel : ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMatrixEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMatrixEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InToOneSeatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InToOneSeatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConferenceModel.ConferenceMatrixWebservice.SeatEntity[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceMatrixWebserviceSoapClient : System.ServiceModel.ClientBase<ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixWebserviceSoap>, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixWebserviceSoap {
        
        private BeginOperationDelegate onBeginSetMatrixEntityDelegate;
        
        private EndOperationDelegate onEndSetMatrixEntityDelegate;
        
        private System.Threading.SendOrPostCallback onSetMatrixEntityCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMatrixEntityDelegate;
        
        private EndOperationDelegate onEndGetMatrixEntityDelegate;
        
        private System.Threading.SendOrPostCallback onGetMatrixEntityCompletedDelegate;
        
        private BeginOperationDelegate onBeginApplyMatrixEntityDelegate;
        
        private EndOperationDelegate onEndApplyMatrixEntityDelegate;
        
        private System.Threading.SendOrPostCallback onApplyMatrixEntityCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendMaxtrixControlCodeDelegate;
        
        private EndOperationDelegate onEndSendMaxtrixControlCodeDelegate;
        
        private System.Threading.SendOrPostCallback onSendMaxtrixControlCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginInToOneSeatDelegate;
        
        private EndOperationDelegate onEndInToOneSeatDelegate;
        
        private System.Threading.SendOrPostCallback onInToOneSeatCompletedDelegate;
        
        private BeginOperationDelegate onBeginLeaveOneSeatDelegate;
        
        private EndOperationDelegate onEndLeaveOneSeatDelegate;
        
        private System.Threading.SendOrPostCallback onLeaveOneSeatCompletedDelegate;
        
        public ConferenceMatrixWebserviceSoapClient() {
        }
        
        public ConferenceMatrixWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceMatrixWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceMatrixWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceMatrixWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetMatrixEntityCompleted;
        
        public event System.EventHandler<GetMatrixEntityCompletedEventArgs> GetMatrixEntityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ApplyMatrixEntityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendMaxtrixControlCodeCompleted;
        
        public event System.EventHandler<InToOneSeatCompletedEventArgs> InToOneSeatCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LeaveOneSeatCompleted;
        
        public void SetMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity) {
            base.Channel.SetMatrixEntity(conferenceID, conferenceMatrixEntity);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSetMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetMatrixEntity(conferenceID, conferenceMatrixEntity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSetMatrixEntity(System.IAsyncResult result) {
            base.Channel.EndSetMatrixEntity(result);
        }
        
        private System.IAsyncResult OnBeginSetMatrixEntity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity = ((ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity)(inValues[1]));
            return this.BeginSetMatrixEntity(conferenceID, conferenceMatrixEntity, callback, asyncState);
        }
        
        private object[] OnEndSetMatrixEntity(System.IAsyncResult result) {
            this.EndSetMatrixEntity(result);
            return null;
        }
        
        private void OnSetMatrixEntityCompleted(object state) {
            if ((this.SetMatrixEntityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetMatrixEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetMatrixEntityAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity) {
            this.SetMatrixEntityAsync(conferenceID, conferenceMatrixEntity, null);
        }
        
        public void SetMatrixEntityAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity conferenceMatrixEntity, object userState) {
            if ((this.onBeginSetMatrixEntityDelegate == null)) {
                this.onBeginSetMatrixEntityDelegate = new BeginOperationDelegate(this.OnBeginSetMatrixEntity);
            }
            if ((this.onEndSetMatrixEntityDelegate == null)) {
                this.onEndSetMatrixEntityDelegate = new EndOperationDelegate(this.OnEndSetMatrixEntity);
            }
            if ((this.onSetMatrixEntityCompletedDelegate == null)) {
                this.onSetMatrixEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetMatrixEntityCompleted);
            }
            base.InvokeAsync(this.onBeginSetMatrixEntityDelegate, new object[] {
                        conferenceID,
                        conferenceMatrixEntity}, this.onEndSetMatrixEntityDelegate, this.onSetMatrixEntityCompletedDelegate, userState);
        }
        
        public ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity GetMatrixEntity(int conferenceID) {
            return base.Channel.GetMatrixEntity(conferenceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMatrixEntity(int conferenceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMatrixEntity(conferenceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity EndGetMatrixEntity(System.IAsyncResult result) {
            return base.Channel.EndGetMatrixEntity(result);
        }
        
        private System.IAsyncResult OnBeginGetMatrixEntity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            return this.BeginGetMatrixEntity(conferenceID, callback, asyncState);
        }
        
        private object[] OnEndGetMatrixEntity(System.IAsyncResult result) {
            ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixEntity retVal = this.EndGetMatrixEntity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMatrixEntityCompleted(object state) {
            if ((this.GetMatrixEntityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMatrixEntityCompleted(this, new GetMatrixEntityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMatrixEntityAsync(int conferenceID) {
            this.GetMatrixEntityAsync(conferenceID, null);
        }
        
        public void GetMatrixEntityAsync(int conferenceID, object userState) {
            if ((this.onBeginGetMatrixEntityDelegate == null)) {
                this.onBeginGetMatrixEntityDelegate = new BeginOperationDelegate(this.OnBeginGetMatrixEntity);
            }
            if ((this.onEndGetMatrixEntityDelegate == null)) {
                this.onEndGetMatrixEntityDelegate = new EndOperationDelegate(this.OnEndGetMatrixEntity);
            }
            if ((this.onGetMatrixEntityCompletedDelegate == null)) {
                this.onGetMatrixEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMatrixEntityCompleted);
            }
            base.InvokeAsync(this.onBeginGetMatrixEntityDelegate, new object[] {
                        conferenceID}, this.onEndGetMatrixEntityDelegate, this.onGetMatrixEntityCompletedDelegate, userState);
        }
        
        public void ApplyMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity) {
            base.Channel.ApplyMatrixEntity(conferenceID, conferenceMaxtrixApplyEntity);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginApplyMatrixEntity(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginApplyMatrixEntity(conferenceID, conferenceMaxtrixApplyEntity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndApplyMatrixEntity(System.IAsyncResult result) {
            base.Channel.EndApplyMatrixEntity(result);
        }
        
        private System.IAsyncResult OnBeginApplyMatrixEntity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity = ((ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity)(inValues[1]));
            return this.BeginApplyMatrixEntity(conferenceID, conferenceMaxtrixApplyEntity, callback, asyncState);
        }
        
        private object[] OnEndApplyMatrixEntity(System.IAsyncResult result) {
            this.EndApplyMatrixEntity(result);
            return null;
        }
        
        private void OnApplyMatrixEntityCompleted(object state) {
            if ((this.ApplyMatrixEntityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ApplyMatrixEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ApplyMatrixEntityAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity) {
            this.ApplyMatrixEntityAsync(conferenceID, conferenceMaxtrixApplyEntity, null);
        }
        
        public void ApplyMatrixEntityAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMaxtrixApplyEntity conferenceMaxtrixApplyEntity, object userState) {
            if ((this.onBeginApplyMatrixEntityDelegate == null)) {
                this.onBeginApplyMatrixEntityDelegate = new BeginOperationDelegate(this.OnBeginApplyMatrixEntity);
            }
            if ((this.onEndApplyMatrixEntityDelegate == null)) {
                this.onEndApplyMatrixEntityDelegate = new EndOperationDelegate(this.OnEndApplyMatrixEntity);
            }
            if ((this.onApplyMatrixEntityCompletedDelegate == null)) {
                this.onApplyMatrixEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnApplyMatrixEntityCompleted);
            }
            base.InvokeAsync(this.onBeginApplyMatrixEntityDelegate, new object[] {
                        conferenceID,
                        conferenceMaxtrixApplyEntity}, this.onEndApplyMatrixEntityDelegate, this.onApplyMatrixEntityCompletedDelegate, userState);
        }
        
        public void SendMaxtrixControlCode(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode) {
            base.Channel.SendMaxtrixControlCode(conferenceID, conferenceMatrixThrowCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendMaxtrixControlCode(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendMaxtrixControlCode(conferenceID, conferenceMatrixThrowCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSendMaxtrixControlCode(System.IAsyncResult result) {
            base.Channel.EndSendMaxtrixControlCode(result);
        }
        
        private System.IAsyncResult OnBeginSendMaxtrixControlCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode = ((ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode)(inValues[1]));
            return this.BeginSendMaxtrixControlCode(conferenceID, conferenceMatrixThrowCode, callback, asyncState);
        }
        
        private object[] OnEndSendMaxtrixControlCode(System.IAsyncResult result) {
            this.EndSendMaxtrixControlCode(result);
            return null;
        }
        
        private void OnSendMaxtrixControlCodeCompleted(object state) {
            if ((this.SendMaxtrixControlCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendMaxtrixControlCodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendMaxtrixControlCodeAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode) {
            this.SendMaxtrixControlCodeAsync(conferenceID, conferenceMatrixThrowCode, null);
        }
        
        public void SendMaxtrixControlCodeAsync(int conferenceID, ConferenceModel.ConferenceMatrixWebservice.ConferenceMatrixThrowCode conferenceMatrixThrowCode, object userState) {
            if ((this.onBeginSendMaxtrixControlCodeDelegate == null)) {
                this.onBeginSendMaxtrixControlCodeDelegate = new BeginOperationDelegate(this.OnBeginSendMaxtrixControlCode);
            }
            if ((this.onEndSendMaxtrixControlCodeDelegate == null)) {
                this.onEndSendMaxtrixControlCodeDelegate = new EndOperationDelegate(this.OnEndSendMaxtrixControlCode);
            }
            if ((this.onSendMaxtrixControlCodeCompletedDelegate == null)) {
                this.onSendMaxtrixControlCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMaxtrixControlCodeCompleted);
            }
            base.InvokeAsync(this.onBeginSendMaxtrixControlCodeDelegate, new object[] {
                        conferenceID,
                        conferenceMatrixThrowCode}, this.onEndSendMaxtrixControlCodeDelegate, this.onSendMaxtrixControlCodeCompletedDelegate, userState);
        }
        
        public ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] InToOneSeat(int conferenceID, string seatList, string selfUri, string selfName, string selfIP) {
            return base.Channel.InToOneSeat(conferenceID, seatList, selfUri, selfName, selfIP);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInToOneSeat(int conferenceID, string seatList, string selfUri, string selfName, string selfIP, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInToOneSeat(conferenceID, seatList, selfUri, selfName, selfIP, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] EndInToOneSeat(System.IAsyncResult result) {
            return base.Channel.EndInToOneSeat(result);
        }
        
        private System.IAsyncResult OnBeginInToOneSeat(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string seatList = ((string)(inValues[1]));
            string selfUri = ((string)(inValues[2]));
            string selfName = ((string)(inValues[3]));
            string selfIP = ((string)(inValues[4]));
            return this.BeginInToOneSeat(conferenceID, seatList, selfUri, selfName, selfIP, callback, asyncState);
        }
        
        private object[] OnEndInToOneSeat(System.IAsyncResult result) {
            ConferenceModel.ConferenceMatrixWebservice.SeatEntity[] retVal = this.EndInToOneSeat(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInToOneSeatCompleted(object state) {
            if ((this.InToOneSeatCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InToOneSeatCompleted(this, new InToOneSeatCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InToOneSeatAsync(int conferenceID, string seatList, string selfUri, string selfName, string selfIP) {
            this.InToOneSeatAsync(conferenceID, seatList, selfUri, selfName, selfIP, null);
        }
        
        public void InToOneSeatAsync(int conferenceID, string seatList, string selfUri, string selfName, string selfIP, object userState) {
            if ((this.onBeginInToOneSeatDelegate == null)) {
                this.onBeginInToOneSeatDelegate = new BeginOperationDelegate(this.OnBeginInToOneSeat);
            }
            if ((this.onEndInToOneSeatDelegate == null)) {
                this.onEndInToOneSeatDelegate = new EndOperationDelegate(this.OnEndInToOneSeat);
            }
            if ((this.onInToOneSeatCompletedDelegate == null)) {
                this.onInToOneSeatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInToOneSeatCompleted);
            }
            base.InvokeAsync(this.onBeginInToOneSeatDelegate, new object[] {
                        conferenceID,
                        seatList,
                        selfUri,
                        selfName,
                        selfIP}, this.onEndInToOneSeatDelegate, this.onInToOneSeatCompletedDelegate, userState);
        }
        
        public void LeaveOneSeat(int conferenceID, string selfName, string selfIP) {
            base.Channel.LeaveOneSeat(conferenceID, selfName, selfIP);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLeaveOneSeat(int conferenceID, string selfName, string selfIP, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLeaveOneSeat(conferenceID, selfName, selfIP, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLeaveOneSeat(System.IAsyncResult result) {
            base.Channel.EndLeaveOneSeat(result);
        }
        
        private System.IAsyncResult OnBeginLeaveOneSeat(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int conferenceID = ((int)(inValues[0]));
            string selfName = ((string)(inValues[1]));
            string selfIP = ((string)(inValues[2]));
            return this.BeginLeaveOneSeat(conferenceID, selfName, selfIP, callback, asyncState);
        }
        
        private object[] OnEndLeaveOneSeat(System.IAsyncResult result) {
            this.EndLeaveOneSeat(result);
            return null;
        }
        
        private void OnLeaveOneSeatCompleted(object state) {
            if ((this.LeaveOneSeatCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LeaveOneSeatCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LeaveOneSeatAsync(int conferenceID, string selfName, string selfIP) {
            this.LeaveOneSeatAsync(conferenceID, selfName, selfIP, null);
        }
        
        public void LeaveOneSeatAsync(int conferenceID, string selfName, string selfIP, object userState) {
            if ((this.onBeginLeaveOneSeatDelegate == null)) {
                this.onBeginLeaveOneSeatDelegate = new BeginOperationDelegate(this.OnBeginLeaveOneSeat);
            }
            if ((this.onEndLeaveOneSeatDelegate == null)) {
                this.onEndLeaveOneSeatDelegate = new EndOperationDelegate(this.OnEndLeaveOneSeat);
            }
            if ((this.onLeaveOneSeatCompletedDelegate == null)) {
                this.onLeaveOneSeatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLeaveOneSeatCompleted);
            }
            base.InvokeAsync(this.onBeginLeaveOneSeatDelegate, new object[] {
                        conferenceID,
                        selfName,
                        selfIP}, this.onEndLeaveOneSeatDelegate, this.onLeaveOneSeatCompletedDelegate, userState);
        }
    }
}
